apiVersion: apps/v1
kind: Deployment

metadata:
  name: webapp #Name has to be name but not functional just for human read

spec:
  replicas: 1
  selector:
      matchLabels:    
        app: webapp   #same as below label
  template:           #pod info
    metadata:
      labels:
        app: webapp   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: quene #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: quene

  template:
    metadata:    
      labels:
        app: quene   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: position-simulator #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: position-simulator

  template:
    metadata:    
      labels:
        app: position-simulator   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: position-tracker #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: position-tracker

  template:
    metadata:    
      labels:
        app: position-tracker   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: api-gateway

  template:
    metadata:    
      labels:
        app: api-gateway   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: api-gateway
        image: richardchesterwood/k8s-fleetman-api-gateway:release2
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice