apiVersion: v1
kind: Pod

metadata:
  name: webapp-release-0-5    #Name has to be name but not functional just for human read
  labels:
    app: webapp   #labels can be named as anything example, yournametag: abc
    release: 0-5

spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod

metadata:
  name: quene    #Name has to be name but not functional just for human read
  labels:
    app: quene   #labels can be named as anything example, yournametag: abc
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1