apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: webapp #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: webapp

  template: 
    metadata:
      labels:
        app: webapp   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: quene #Name has to be name but not functional just for human read

spec:
  replicas: 1

  selector:
      matchLabels:
        app: quene

  template:
    metadata:    
      labels:
        app: quene   #labels can be named as anything example, yournametag: abc
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1