apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #This defines which pods are going to controled by service
  #This will set network endpoint
  selector:
    app: webapp    #relate to pod label

  ports:
  - name: http        #just label not functional
    port: 80          #internal port (inside k8s env)
    targetPort: 80    #app port (app spec)
    nodePort: 30080   #to external port (world network)

  type: NodePort      #NodePort go outside/ loadbalancer is support for loadbalance/ ClusterIP is for internal use(no go outside)

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-quene

spec:
  selector:
    app: quene    
  ports:
  - name: http        
    port: 8161          
    targetPort: 8161    
    nodePort: 30010   

  type: NodePort      
